apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-storage
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/mysql-storage"


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dados
spec:
  resources:
    requests:
      storage: 10Gi  
  accessModes:
    - ReadWriteOnce
  storageClassName: manual

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: marneumann/projeto-k8s-database:1.0
        args:
        - "--ignore-db-dir=lost+found"
        imagePullPolicy: Always
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql/
      volumes:
       - name: mysql-data
         persistentVolumeClaim:
           claimName: mysql-dados

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: marneumann/projeto-k8s-backend:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80